#############################################################################
# Makefile for building: qtmobilehotspot
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Nov 13 00:20:37 2011
# Project:  qtmobilehotspot.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile qtmobilehotspot.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qtMobileHotspot \
		sub-qtmhDummy \
		sub-qtmhNetFix \
		sub-qtmhIptablesFix \
		sub-qtmhMacFilter \
		sub-qtmhDNSMasq \
		sub-qtmhPrivoxy

qtMobileHotspot/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtMobileHotspot/ || $(MKDIR) qtMobileHotspot/ 
	cd qtMobileHotspot/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtMobileHotspot/qtMobileHotspot.pro -o $(MAKEFILE)
sub-qtMobileHotspot-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtMobileHotspot/ || $(MKDIR) qtMobileHotspot/ 
	cd qtMobileHotspot/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtMobileHotspot/qtMobileHotspot.pro -o $(MAKEFILE)
sub-qtMobileHotspot: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE)
sub-qtMobileHotspot-make_default: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) 
sub-qtMobileHotspot-make_first: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) first
sub-qtMobileHotspot-all: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) all
sub-qtMobileHotspot-clean: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtMobileHotspot-distclean: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtMobileHotspot-install_subtargets: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) install
sub-qtMobileHotspot-uninstall_subtargets: qtMobileHotspot/$(MAKEFILE) FORCE
	cd qtMobileHotspot/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhDummy/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhDummy/ || $(MKDIR) qtmhDummy/ 
	cd qtmhDummy/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhDummy/qtmhDummy.pro -o $(MAKEFILE)
sub-qtmhDummy-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhDummy/ || $(MKDIR) qtmhDummy/ 
	cd qtmhDummy/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhDummy/qtmhDummy.pro -o $(MAKEFILE)
sub-qtmhDummy: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhDummy-make_default: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhDummy-make_first: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhDummy-all: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhDummy-clean: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhDummy-distclean: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhDummy-install_subtargets: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhDummy-uninstall_subtargets: qtmhDummy/$(MAKEFILE) FORCE
	cd qtmhDummy/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhNetFix/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhNetFix/ || $(MKDIR) qtmhNetFix/ 
	cd qtmhNetFix/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhNetFix/qtmhNetFix.pro -o $(MAKEFILE)
sub-qtmhNetFix-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhNetFix/ || $(MKDIR) qtmhNetFix/ 
	cd qtmhNetFix/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhNetFix/qtmhNetFix.pro -o $(MAKEFILE)
sub-qtmhNetFix: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhNetFix-make_default: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhNetFix-make_first: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhNetFix-all: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhNetFix-clean: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhNetFix-distclean: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhNetFix-install_subtargets: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhNetFix-uninstall_subtargets: qtmhNetFix/$(MAKEFILE) FORCE
	cd qtmhNetFix/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhIptablesFix/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhIptablesFix/ || $(MKDIR) qtmhIptablesFix/ 
	cd qtmhIptablesFix/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhIptablesFix/qtmhIptablesFix.pro -o $(MAKEFILE)
sub-qtmhIptablesFix-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhIptablesFix/ || $(MKDIR) qtmhIptablesFix/ 
	cd qtmhIptablesFix/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhIptablesFix/qtmhIptablesFix.pro -o $(MAKEFILE)
sub-qtmhIptablesFix: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhIptablesFix-make_default: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhIptablesFix-make_first: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhIptablesFix-all: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhIptablesFix-clean: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhIptablesFix-distclean: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhIptablesFix-install_subtargets: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhIptablesFix-uninstall_subtargets: qtmhIptablesFix/$(MAKEFILE) FORCE
	cd qtmhIptablesFix/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhMacFilter/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhMacFilter/ || $(MKDIR) qtmhMacFilter/ 
	cd qtmhMacFilter/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhMacFilter/qtmhMacFilter.pro -o $(MAKEFILE)
sub-qtmhMacFilter-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhMacFilter/ || $(MKDIR) qtmhMacFilter/ 
	cd qtmhMacFilter/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhMacFilter/qtmhMacFilter.pro -o $(MAKEFILE)
sub-qtmhMacFilter: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhMacFilter-make_default: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhMacFilter-make_first: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhMacFilter-all: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhMacFilter-clean: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhMacFilter-distclean: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhMacFilter-install_subtargets: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhMacFilter-uninstall_subtargets: qtmhMacFilter/$(MAKEFILE) FORCE
	cd qtmhMacFilter/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhDNSMasq/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhDNSMasq/ || $(MKDIR) qtmhDNSMasq/ 
	cd qtmhDNSMasq/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhDNSMasq/qtmhDNSMasq.pro -o $(MAKEFILE)
sub-qtmhDNSMasq-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhDNSMasq/ || $(MKDIR) qtmhDNSMasq/ 
	cd qtmhDNSMasq/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhDNSMasq/qtmhDNSMasq.pro -o $(MAKEFILE)
sub-qtmhDNSMasq: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhDNSMasq-make_default: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhDNSMasq-make_first: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhDNSMasq-all: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhDNSMasq-clean: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhDNSMasq-distclean: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhDNSMasq-install_subtargets: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhDNSMasq-uninstall_subtargets: qtmhDNSMasq/$(MAKEFILE) FORCE
	cd qtmhDNSMasq/ && $(MAKE) -f $(MAKEFILE) uninstall
qtmhPrivoxy/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qtmhPrivoxy/ || $(MKDIR) qtmhPrivoxy/ 
	cd qtmhPrivoxy/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhPrivoxy/qtmhPrivoxy.pro -o $(MAKEFILE)
sub-qtmhPrivoxy-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qtmhPrivoxy/ || $(MKDIR) qtmhPrivoxy/ 
	cd qtmhPrivoxy/ && $(QMAKE) /home/dest/workspace/qtmobilehotspot/qtmhPrivoxy/qtmhPrivoxy.pro -o $(MAKEFILE)
sub-qtmhPrivoxy: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE)
sub-qtmhPrivoxy-make_default: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) 
sub-qtmhPrivoxy-make_first: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) first
sub-qtmhPrivoxy-all: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) all
sub-qtmhPrivoxy-clean: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) clean
sub-qtmhPrivoxy-distclean: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qtmhPrivoxy-install_subtargets: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) install
sub-qtmhPrivoxy-uninstall_subtargets: qtmhPrivoxy/$(MAKEFILE) FORCE
	cd qtmhPrivoxy/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qtmobilehotspot.pro  /targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/linux-g++-maemo5/qmake.conf /targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qtmobilehotspot.pro
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/unix.conf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/common/linux.conf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/qconfig.pri:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/release.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/qt.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/moc.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/resources.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/uic.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/lex.prf:
/targets/FREMANTLE_ARMEL/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qtmobilehotspot.pro

qmake_all: sub-qtMobileHotspot-qmake_all sub-qtmhDummy-qmake_all sub-qtmhNetFix-qmake_all sub-qtmhIptablesFix-qmake_all sub-qtmhMacFilter-qmake_all sub-qtmhDNSMasq-qmake_all sub-qtmhPrivoxy-qmake_all FORCE

make_default: sub-qtMobileHotspot-make_default sub-qtmhDummy-make_default sub-qtmhNetFix-make_default sub-qtmhIptablesFix-make_default sub-qtmhMacFilter-make_default sub-qtmhDNSMasq-make_default sub-qtmhPrivoxy-make_default FORCE
make_first: sub-qtMobileHotspot-make_first sub-qtmhDummy-make_first sub-qtmhNetFix-make_first sub-qtmhIptablesFix-make_first sub-qtmhMacFilter-make_first sub-qtmhDNSMasq-make_first sub-qtmhPrivoxy-make_first FORCE
all: sub-qtMobileHotspot-all sub-qtmhDummy-all sub-qtmhNetFix-all sub-qtmhIptablesFix-all sub-qtmhMacFilter-all sub-qtmhDNSMasq-all sub-qtmhPrivoxy-all FORCE
clean: sub-qtMobileHotspot-clean sub-qtmhDummy-clean sub-qtmhNetFix-clean sub-qtmhIptablesFix-clean sub-qtmhMacFilter-clean sub-qtmhDNSMasq-clean sub-qtmhPrivoxy-clean FORCE
distclean: sub-qtMobileHotspot-distclean sub-qtmhDummy-distclean sub-qtmhNetFix-distclean sub-qtmhIptablesFix-distclean sub-qtmhMacFilter-distclean sub-qtmhDNSMasq-distclean sub-qtmhPrivoxy-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qtMobileHotspot-install_subtargets sub-qtmhDummy-install_subtargets sub-qtmhNetFix-install_subtargets sub-qtmhIptablesFix-install_subtargets sub-qtmhMacFilter-install_subtargets sub-qtmhDNSMasq-install_subtargets sub-qtmhPrivoxy-install_subtargets FORCE
uninstall_subtargets: sub-qtMobileHotspot-uninstall_subtargets sub-qtmhDummy-uninstall_subtargets sub-qtmhNetFix-uninstall_subtargets sub-qtmhIptablesFix-uninstall_subtargets sub-qtmhMacFilter-uninstall_subtargets sub-qtmhDNSMasq-uninstall_subtargets sub-qtmhPrivoxy-uninstall_subtargets FORCE

sub-qtMobileHotspot-check: qtMobileHotspot/$(MAKEFILE)
	cd qtMobileHotspot/ && $(MAKE) check
sub-qtmhDummy-check: qtmhDummy/$(MAKEFILE)
	cd qtmhDummy/ && $(MAKE) check
sub-qtmhNetFix-check: qtmhNetFix/$(MAKEFILE)
	cd qtmhNetFix/ && $(MAKE) check
sub-qtmhIptablesFix-check: qtmhIptablesFix/$(MAKEFILE)
	cd qtmhIptablesFix/ && $(MAKE) check
sub-qtmhMacFilter-check: qtmhMacFilter/$(MAKEFILE)
	cd qtmhMacFilter/ && $(MAKE) check
sub-qtmhDNSMasq-check: qtmhDNSMasq/$(MAKEFILE)
	cd qtmhDNSMasq/ && $(MAKE) check
sub-qtmhPrivoxy-check: qtmhPrivoxy/$(MAKEFILE)
	cd qtmhPrivoxy/ && $(MAKE) check
check: sub-qtMobileHotspot-check sub-qtmhDummy-check sub-qtmhNetFix-check sub-qtmhIptablesFix-check sub-qtmhMacFilter-check sub-qtmhDNSMasq-check sub-qtmhPrivoxy-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

